runtime: python39
entrypoint: python debug_path.py && gunicorn chainstory.asgi:application -b :$PORT -k uvicorn.workers.UvicornWorker

env_variables:
  DJANGO_ENV: "production"
  DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
  DJANGO_SETTINGS_MODULE: "chainstory.settings"
  DEBUG: "False"

handlers:
- url: /static
  static_dir: staticfiles
  secure: always
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10 